# Generated by Django 2.1.5 on 2020-02-18 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_nominalroll_saved_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceformat',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='attendanceformat',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='attendanceformat',
            name='email',
        ),
        migrations.RemoveField(
            model_name='attendanceformat',
            name='student_id',
        ),
    ]
