# Generated by Django 2.1.5 on 2020-02-18 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200218_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceformat',
            old_name='name',
            new_name='classroom',
        ),
    ]
